/** The built-in "Default" layout — rebuilt from this constant rather than reconstructed panel-by-panel
 * (an earlier version built it that way and got hierarchy's width wrong: dockview's initialWidth is a
 * no-op on a panel that's still alone in an empty grid, which is exactly what building "from scratch"
 * requires). It's the same StoredLayout envelope WorkspaceContext.applyLayout()/serializeLayout() use for
 * saved profiles (dockview's own serialized tree plus which tool windows are open/auto-hidden) — captured
 * by hand-arranging the workspace and saving it as a layout profile, then copying that profile's
 * `layoutJson` here. To replace it: arrange the workspace, View > Manage Layouts… > save it under any
 * name, copy its layoutJson from preferences.json, paste it below, then delete that temporary profile. */
export const DEFAULT_LAYOUT_JSON =
  '{"dockview":{"grid":{"root":{"type":"branch","data":[{"type":"branch","data":[{"type":"leaf","data":{"views":["hierarchy"],"activeView":"hierarchy","id":"6"},"size":287},{"type":"leaf","data":{"views":["toolbox"],"activeView":"toolbox","id":"9"},"size":285}],"size":178},{"type":"leaf","data":{"views":["document"],"activeView":"document","id":"7","hideHeader":true},"size":732},{"type":"leaf","data":{"views":["properties"],"activeView":"properties","id":"8"},"size":240}],"size":572},"width":1150,"height":572,"orientation":"HORIZONTAL"},"panels":{"toolbox":{"id":"toolbox","contentComponent":"toolWindow","tabComponent":"props.defaultTabComponent","params":{"toolWindowId":"toolbox"},"title":"Toolbox","minimumHeight":100,"minimumWidth":160},"hierarchy":{"id":"hierarchy","contentComponent":"toolWindow","tabComponent":"props.defaultTabComponent","params":{"toolWindowId":"hierarchy"},"title":"Hierarchy","minimumHeight":120,"minimumWidth":160},"document":{"id":"document","contentComponent":"document","tabComponent":"props.defaultTabComponent","title":"Document"},"properties":{"id":"properties","contentComponent":"toolWindow","tabComponent":"props.defaultTabComponent","params":{"toolWindowId":"properties"},"title":"Properties","minimumHeight":160,"minimumWidth":240}},"activeGroup":"9"},"openIds":["hierarchy","toolbox","properties","errorList"],"autoHiddenIds":["errorList"]}';
